name: jua_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - boto3
  - botocore
  - xarray
  - pip:
      - h3==4.0.0b1
      - h5netcdf
      - pyarrow
      - fastparquet